packages:
  - '.'
  - 'backend/*'
  - 'frontend/*'
  - 'agent'
  - 'dukat-voice-saas-backend'
  - 'integrations/*'
  - 'sdk/*'
  - 'audio-processing/*'
  - 'databases/*'
  - 'deployment/*'
  - 'infrastructure/*'
  - 'monitoring/*'
  - 'security'